export const data = [
  {
    id: 1,
    title: "SoundHelix Song 1",
    artist: "Generic Artist 1",
    src: "../audio/SoundHelix-Song-1.mp3",
    cover: "../OIP.jpeg",
    artistCover: "./OIP (1).jpeg",
    like: true,
  },
  {
    id: 2,
    title: "SoundHelix Song 2",
    artist: "Generic Artist 2",
    src: "../audio/SoundHelix-Song-2.mp3",
    cover: "../OIP.jpeg",
    artistCover: "./OIP (1).jpeg",
    like: false,
  },
  {
    id: 3,
    title: "SoundHelix Song 3",
    artist: "Generic Artist 1",
    src: "../audio/SoundHelix-Song-3.mp3",
    cover: "../OIP.jpeg",
    artistCover: "./OIP (1).jpeg",
    like: true,
  },
  {
    id: 4,
    title: "SoundHelix Song 4",
    artist: "Generic Artist 4",
    src: "../audio/SoundHelix-Song-4.mp3",
    cover: "../OIP.jpeg",
    artistCover: "./OIP (1).jpeg",
    like: false,
  },
  {
    id: 5,
    title: "SoundHelix Song 5",
    artist: "Generic Artist 5",
    src: "../audio/SoundHelix-Song-5.mp3",
    cover: "../OIP.jpeg",
    artistCover: "./OIP (1).jpeg",
    like: false,
  },
  {
    id: 6,
    title: "SoundHelix Song 6",
    artist: "Generic Artist 3",
    src: "../audio/SoundHelix-Song-6.mp3",
    cover: "../OIP.jpeg",
    artistCover: "./OIP (1).jpeg",
    like: true,
  },
  {
    id: 7,
    title: "SoundHelix Song 7",
    artist: "Generic Artist 2",
    src: "../audio/SoundHelix-Song-7.mp3",
    cover: "../OIP.jpeg",
    artistCover: "./OIP (1).jpeg",
    like: false,
  },
  {
    id: 8,
    title: "SoundHelix Song 8",
    artist: "Generic Artist 4",
    src: "../audio/SoundHelix-Song-8.mp3",
    cover: "../OIP.jpeg",
    artistCover: "./OIP (1).jpeg",
    like: true,
  },
  {
    id: 9,
    title: "SoundHelix Song 9",
    artist: "Generic Artist 6",
    src: "../audio/SoundHelix-Song-9.mp3",
    cover: "../OIP.jpeg",
    artistCover: "./OIP (1).jpeg",
    like: false,
  },
  {
    id: 10,
    title: "SoundHelix Song 10",
    artist: "Generic Artist 1",
    src: "../audio/SoundHelix-Song-10.mp3",
    cover: "../OIP.jpeg",
    artistCover: "./OIP (1).jpeg",
    like: false,
  },
  {
    id: 11,
    title: "SoundHelix Song 11",
    artist: "Generic Artist 5",
    src: "../audio/SoundHelix-Song-11.mp3",
    cover: "../OIP.jpeg",
    artistCover: "./OIP (1).jpeg",
    like: true,
  },
  {
    id: 12,
    title: "SoundHelix Song 12",
    artist: "Generic Artist 6",
    src: "../audio/SoundHelix-Song-12.mp3",
    cover: "../OIP.jpeg",
    artistCover: "./OIP (1).jpeg",
    like: true,
  },
  {
    id: 13,
    title: "SoundHelix Song 13",
    artist: "Generic Artist 3",
    src: "../audio/SoundHelix-Song-13.mp3",
    cover: "../OIP.jpeg",
    artistCover: "./OIP (1).jpeg",
    like: false,
  },
  {
    id: 14,
    title: "SoundHelix Song 14",
    artist: "Generic Artist 6",
    src: "../audio/SoundHelix-Song-14.mp3",
    cover: "../OIP.jpeg",
    artistCover: "./OIP (1).jpeg",
    like: false,
  },
  {
    id: 15,
    title: "SoundHelix Song 15",
    artist: "Generic Artist 2",
    src: "../audio/SoundHelix-Song-15.mp3",
    cover: "../OIP.jpeg",
    artistCover: "./OIP (1).jpeg",
    like: true,
  },
  {
    id: 16,
    title: "SoundHelix Song 16",
    artist: "Generic Artist 5",
    src: "../audio/SoundHelix-Song-16.mp3",
    cover: "../OIP.jpeg",
    artistCover: "./OIP (1).jpeg",
    like: false,
  },
  {
    id: 17,
    title: "SoundHelix Song 17",
    artist: "Generic Artist 4",
    src: "../audio/SoundHelix-Song-17.mp3",
    cover: "../OIP.jpeg",
    artistCover: "./OIP (1).jpeg",
    like: true,
  },
];
